use_frameworks!
inhibit_all_warnings!
platform :ios, '9.0'

target 'GFGeneralLib_Example' do
  pod 'GFGeneralLib', :path => '../'

  target 'GFGeneralLib_Tests' do
    inherit! :search_paths

  end
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
    end
  end
end


